name = "sabi-marketplace"
main = "worker.js"
compatibility_date = "2026-09-29"

[assets]
directory = "./public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "sabi-marketplace"
database_id = "3511d34c-8a6c-4972-b4c9-bd73cb0a9de3"
